### ISSUE TITLE
Adding alias to exprs_values argument

### ISSUE THREAD

**Issue by antagomir** [LTLA/scuttle#21]
The _scater_ package has added deprecation message on the `exprs_values` argument and replaced this with `assay_name` as the argument to choose the assay for plotting SE objects. See [scater PR #187](https://github.com/Alanocallaghan/scater/pull/187). Also the [mia](https://github.com/microbiome/mia) family of packages (for microbiome analysis) are using the `assay_name` argument.

The `assay_name` refers more explicitly to assays than `exprs_values`. 

I suggest to make the same change in the _scuttle_ package. We can prepare a PR if this suggestion is supported: deprecate `exprs_values`, replace it with `assay_name`, and use former as an alias for the latter.

**Comment by LTLA** [comment]
`exprs_values` (and all other underscore arguments in **scuttle**) is soft-deprecated, as I prefer to use:

- dots as separators in argument names
- lower camel case in function names
- upper camel case in class names
- underscores in internal function names

Right now, I only keep the underscore'd arguments around to avoid breaking existing code, owing to the history of some of the **scuttle** functions that were ported from and then re-exported in **scater**. It would not be desirable to transition from one underscore'd argument to another when I want people to use the dot arguments (`assay.type`).

**Comment by Alanocallaghan** [comment]
Small correction, `exprs_values` isn't deprecated

**Comment by antagomir** [comment]
The _mia*_ and _scater_ packages have switched to using `assay.type` now.
