### ISSUE TITLE
summarizeAssayByGroup output has NULL colnames when ids is a DataFrame

### ISSUE THREAD

**Issue by alanocallaghan** [LTLA/scuttle#25]
From `example(summarizeAssayByGroup)`. Is this intended behaviour?

```r
example_sce <- mockSCE()
ids <- sample(LETTERS[1:5], ncol(example_sce), replace=TRUE)
out <- summarizeAssayByGroup(example_sce, ids)

# this is fine
colnames(out)
# [1] "A" "B" "C" "D" "E"


batches <- sample(1:3, ncol(example_sce), replace=TRUE)
out2 <- summarizeAssayByGroup(example_sce, 
      DataFrame(label=ids, batch=batches))

# no colnames because .create_coldata output has no rownames
colnames(out2)
# NULL
```

**Comment by LTLA** [comment]
I think so; I didn't try to construct a column name from unique combinations. I suppose we could just `paste0` the columns together, if people are relying on some column names (but that might not be guaranteed to be unique, e.g., if there is one combination of `A_B` + `C` and another combination of `A` + `B_C` and you did the `paste0` with a `_` separator).

**Comment by alanocallaghan** [comment]
Interesting, came across it in https://github.com/alanocallaghan/scater/issues/200, and I'm now left wondering how long this has been broken/if it ever worked as intended. Cheers
