### ISSUE TITLE
Adding subsets from addPerCellQC to rowData 

### ISSUE THREAD

**Issue by llrs** [LTLA/scuttle#29]
Many thanks for the great resources and books.

When I use `subsets` in `addPerCellQC` I'd like to have the subsets added to the rowData of the SCE the columns identifying which gene was used for each subset.

I can do that manually but I sometimes change the subsets or forget to add the columns. Hence the requests to add this to scuttle. 
Would it be possible to enhance so that it adds it? The column could be the same name as the names on the list.

**Comment by LTLA** [comment]
Sounds reasonable. Can you put together a PR?

**Comment by llrs** [comment]
Closing now that the PR was merged! Thanks!!
