### ISSUE TITLE
Failed to find a rowRanges() method for SingleCellExperiment objects

### ISSUE THREAD

**Issue by YifeiSheng** [LTLA/scuttle#4]
It works well several months ago, but this error reported recently, please help me with it.
`>Mito=grep("mt-", rownames(sce1))
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'grep': Failed to find a rowRanges() method for SingleCellExperiment objects.
`
Thank you in advance

**Comment by LTLA** [comment]
Make sure you have the latest version of _all_ Bioconductor packages. Check the validity of your installation with:

```r
BiocManager::valid()
```
