### ISSUE TITLE
Error: object ‘I’ is not exported by 'namespace:S4Vectors'

### ISSUE THREAD

**Issue by cytogil** [LTLA/scuttle#5]
Error when trying to install scuttle:
`Error: object ‘I’ is not exported by 'namespace:S4Vectors'`

**Comment by LTLA** [comment]
Make sure you are following the [official installation instructions](https://bioconductor.org/packages/scuttle).

**Comment by cytogil** [comment]
Solved the problem. Thank you.
I was following the instructions in:
https://rdrr.io/github/LTLA/scuttle/

**Comment by LTLA** [comment]
Thanks Gil, didn't realize Rdrr produced their own installation instructions. Maybe I should ask them to be a bit smarter about it.
